server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/courses/**
            - id: exam-service
              uri: lb://exam-service
              predicates:
                - Path=/exams/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true